replicaCount: 2  
  
image:  
  repository: 325452764035.dkr.ecr.ap-southeast-1.amazonaws.com/kirito-repo  
  tag: 725e4158c4743b5b263e14281cb64c156523ae6f  
  pullPolicy: IfNotPresent  
  
resources:  
  requests:  
    memory: "64Mi"  
    cpu: "250m"  
  limits:  
    memory: "128Mi"  
    cpu: "500m"  
  
service:  
  type: LoadBalancer  
  port: 80  
  targetPort: 8080  
