replicaCount: 2  
  
image:  
  repository: repo  
  tag: tag  
  pullPolicy: IfNotPresent  
  
resources:  
  requests:  
    memory: "64Mi"  
    cpu: "250m"  
  limits:  
    memory: "128Mi"  
    cpu: "500m"  
  
service:  
  type: LoadBalancer  
  port: 80  
  targetPort: 8080  
